s=set()
n1=int(input("Enter the Number "))
s.add(n1)
n12=int(input("Enter the Number "))
s.add(n12)
n3=int(input("Enter the Number "))
s.add(n3)
n4=int(input("Enter the Number "))
s.add(n4)
n5=int(input("Enter the Number "))
s.add(n5)
n6=int(input("Enter the Number "))
s.add(n6)
n7=int(input("Enter the Number "))
s.add(n7)
n8=int(input("Enter the Number "))
s.add(n8)
print(s)