f=[]
f1 = input("Enter fruit name ")
f.append(f1)
f2 = input("Enter fruit name ")
f.append(f2)
f3 = input("Enter fruit name ")
f.append(f3)
f4 = input("Enter fruit name ")
f.append(f4)
f5 = input("Enter fruit name ")
f.append(f5)
f6 = input("Enter fruit name ")
f.append(f6)
f7 = input("Enter fruit name ")
f.append(f7)
print(f)